# Generated by Django 2.2.6 on 2019-11-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stegnoraphy', '0002_image_iid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='iid',
        ),
    ]
